name: build

on:
  release:
    types:
      - released
  workflow_dispatch: {}

env:
  NODE_BUILD_CMD: npx --no-install prebuild -r node -t 20.0.0 -t 22.0.0 --include-regex 'better_sqlite3.node$' --tag v12.4.4
  ELECTRON_BUILD_CMD: npx --no-install prebuild -r electron -t 39.0.0 --include-regex 'better_sqlite3.node$' --tag v12.4.4

jobs:
  prebuild:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14      # mac.aarch64
          - macos-13      # mac.amd64
          - windows-2022  # windows.amd64
    name: Prebuild on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - if: ${{ startsWith(matrix.os, 'windows') }}
        run: pip.exe install setuptools
      
      - if: ${{ startsWith(matrix.os, 'macos') }}
        run: brew install python-setuptools
      
      - run: npm install --ignore-scripts
      
      - run: ${{ env.NODE_BUILD_CMD }} -u ${{ secrets.GITHUB_TOKEN }}
      
      - run: ${{ env.ELECTRON_BUILD_CMD }} -u ${{ secrets.GITHUB_TOKEN }}
